"""End-to-end result-analysis pipeline."""

from dataclasses import dataclass
from pathlib import Path

from igt.typing import StrPathLike
from igt.utils.io import normalize_path, write_csv

from .config import AnalysisConfig
from .inference import (
    build_criterion_inference_table,
    build_model_win_inference_table,
)
from .io import load_result_tables
from .plots import generate_all_figures
from .report import write_analysis_report
from .tables import (
    build_boundary_summary_table,
    build_model_win_table,
    build_parameter_summary_table,
    build_study_preference_table,
    build_subject_comparison_table,
)
from .validation import validate_result_tables


@dataclass(frozen=True, slots=True)
class AnalysisOutputs:
    """Paths generated by one result-analysis run."""

    output_directory: Path
    report_path: Path
    figure_paths: tuple[Path, ...]
    table_paths: tuple[Path, ...]


def generate_results_analysis(
    fits_path: StrPathLike,
    comparison_path: StrPathLike,
    summary_path: StrPathLike,
    output_directory: StrPathLike,
    *,
    config: AnalysisConfig | None = None,
) -> AnalysisOutputs:
    """Validate result CSVs and generate standard tables and figures."""

    analysis_config = config if config is not None else AnalysisConfig()
    normalized_output_directory = normalize_path(
        output_directory,
        parameter_name="output_directory",
    )
    tables = validate_result_tables(
        load_result_tables(
            fits_path,
            comparison_path,
            summary_path,
        ),
        analysis_config,
    )

    figures_directory = normalized_output_directory / "figures"
    tables_directory = normalized_output_directory / "tables"
    subject_comparison = build_subject_comparison_table(tables.comparison)
    study_preference = build_study_preference_table(subject_comparison)
    boundary_summary = build_boundary_summary_table(tables.fits)
    parameter_summary = build_parameter_summary_table(
        tables.fits,
        analysis_config,
    )
    model_win_table = build_model_win_table(subject_comparison)
    criterion_inference = build_criterion_inference_table(
        subject_comparison,
        analysis_config,
    )
    model_win_inference = build_model_win_inference_table(
        subject_comparison,
        analysis_config,
    )

    table_outputs = {
        "subject_level_model_comparison.csv": subject_comparison,
        "study_model_preference.csv": study_preference,
        "boundary_summary.csv": boundary_summary,
        "parameter_summary.csv": parameter_summary,
        "model_win_summary.csv": model_win_table,
        "criterion_difference_inference.csv": criterion_inference,
        "model_win_inference.csv": model_win_inference,
    }
    table_paths: list[Path] = []

    for filename, data in table_outputs.items():
        output_path = tables_directory / filename
        write_csv(data, output_path)
        table_paths.append(output_path)

    figure_paths = generate_all_figures(
        tables.fits,
        subject_comparison,
        study_preference,
        boundary_summary,
        model_win_table,
        criterion_inference,
        model_win_inference,
        output_directory=figures_directory,
        config=analysis_config,
    )
    report_path = normalized_output_directory / "analysis_report.txt"
    write_analysis_report(
        tables.summary,
        model_win_table,
        study_preference,
        boundary_summary,
        parameter_summary,
        criterion_inference,
        model_win_inference,
        figure_paths,
        tuple(table_paths),
        report_path=report_path,
    )

    return AnalysisOutputs(
        output_directory=normalized_output_directory,
        report_path=report_path,
        figure_paths=figure_paths,
        table_paths=tuple(table_paths),
    )
