import logging

DEFAULT_FIT_METHOD = "L-BFGS-B"
SUBJECTS_AVAILABLE = 617
FIXED_SEED = 1234567890
DEFAULT_MAX_ITERATIONS = 1_000
DEFAULT_N_Q_STARTS = 5
DEFAULT_N_PVL_STARTS = 32
DEFAULT_N_WORKERS = 0
DEFAULT_N_SUBJECTS = -1
DEFAULT_ROOT_LOG_LEVEL = logging.DEBUG
USE_FIXED_SEED = True

FILENAME_DATETIME_FMT = "%Y-%m-%d_%H-%M-%S"

DATETIME_FORMAT = "%Y-%m-%d %H:%M:%S"
LOG_FORMAT = "[%(asctime)s] [%(levelname)s] %(name)s: %(message)s"
TERMINAL_LOG_LEVEL = logging.INFO
FILE_LOG_LEVEL = logging.DEBUG
PAYOFF_SCALE: float = 100.0

OPEN_BOUND_EPSILON = 1e-6

GENERAL_MIN_LEARNING_RATE = 0.0
GENERAL_MAX_LEARNING_RATE = 1.0

MIN_OUTCOME_SENSITIVITY = OPEN_BOUND_EPSILON
MAX_OUTCOME_SENSITIVITY = 2.0

MIN_LOSS_AVERSION = OPEN_BOUND_EPSILON
MAX_LOSS_AVERSION = 10.0

MIN_RESPONSE_CONSISTENCY = 0.0
MAX_RESPONSE_CONSISTENCY = 5.0

MIN_INVERSE_TEMPERATURE = 0.0
MAX_INVERSE_TEMPERATURE = 20.0
